export const sectors = {
  hotel: {
    eyebrow: "AvatarOne per hotel e strutture ricettive",
    title: "Un concierge digitale sempre disponibile.",
    description: "Accoglie gli ospiti, presenta camere e servizi, risponde alle domande frequenti e accompagna ogni richiesta verso reception o WhatsApp.",
    assistant: "ELISA",
    video: "/elisa-avatar-video.mp4",
    poster: "/elisa-avatar-poster.jpg",
    question: "A che ora viene servita la colazione?",
    answer: "La colazione è disponibile ogni mattina. Posso anche aiutarti con servizi, indicazioni e richieste alla reception.",
    benefits: [
      ["24/7", "Accoglienza continua", "Risponde prima, durante e dopo il soggiorno, anche quando la reception è impegnata."],
      ["🌍", "Ospiti internazionali", "Comunica in più lingue e rende più semplice l’accesso alle informazioni utili."],
      ["↗", "Richieste su WhatsApp", "Trasforma la conversazione in un contatto diretto con la struttura."],
      ["▤", "Conosce l’hotel", "Impara da sito, listini, menu, servizi, regolamenti e PDF della struttura."],
    ],
    useCases: ["Camere, orari e disponibilità", "Ristorante, spa e servizi", "Indicazioni e territorio", "Eventi e sale meeting"],
  },
  benessere: {
    eyebrow: "AvatarOne per beauty, spa e benessere",
    title: "La consulente digitale del tuo centro.",
    description: "Presenta trattamenti e prodotti, orienta il cliente verso il percorso più adatto e genera richieste di appuntamento qualificate.",
    assistant: "FRANCESCA",
    video: "/francesca-avatar.mp4",
    poster: "/icon-512.png",
    question: "Quale trattamento è più adatto a me?",
    answer: "Ti spiego i percorsi disponibili e raccolgo le informazioni necessarie per metterti in contatto con il centro.",
    benefits: [
      ["✦", "Consulenza guidata", "Aiuta il cliente a comprendere trattamenti, prodotti e risultati attesi."],
      ["▤", "Listini sempre aggiornati", "Impara da cataloghi, protocolli, promozioni e materiali formativi."],
      ["◉", "Voce e chat", "Il cliente può parlare oppure scrivere direttamente dal proprio smartphone."],
      ["↗", "Prenotazioni e contatti", "Accompagna la richiesta verso WhatsApp o il sistema di prenotazione."],
    ],
    useCases: ["Trattamenti viso e corpo", "Percorsi spa e wellness", "Prodotti e protocolli", "Promozioni e appuntamenti"],
  },
  ristorazione: {
    eyebrow: "AvatarOne per ristoranti e hospitality",
    title: "Il tuo menu prende voce.",
    description: "Racconta piatti, ingredienti e territorio, risponde sulle esigenze alimentari e accompagna il cliente alla prenotazione.",
    assistant: "MIA",
    video: "/mia-avatar-video.mp4",
    poster: "/icon-512.png",
    question: "Mi consigli un primo tipico?",
    answer: "Posso raccontarti i piatti, gli ingredienti e gli abbinamenti, oppure aiutarti a contattare il ristorante.",
    benefits: [
      ["🍽", "Menu interattivo", "Presenta piatti, ingredienti, abbinamenti e storia della cucina."],
      ["◉", "Risposte immediate", "Gestisce le domande frequenti prima che il cliente telefoni al locale."],
      ["🌍", "Accoglienza multilingua", "Facilita la comprensione del menu anche per i clienti internazionali."],
      ["↗", "Prenotazione diretta", "Porta il cliente su WhatsApp o sul canale di prenotazione scelto."],
    ],
    useCases: ["Menu e ingredienti", "Allergeni e preferenze", "Cantina e abbinamenti", "Prenotazioni ed eventi"],
  },
  immobiliare: {
    eyebrow: "AvatarOne per agenzie immobiliari",
    title: "Ogni immobile ha un assistente digitale.",
    description: "Presenta immobili e servizi, raccoglie le esigenze del cliente, qualifica il contatto e facilita la prenotazione di una visita.",
    assistant: "ILARIA",
    video: "/epm-avatar.mp4",
    poster: "/icon-512.png",
    question: "Cerco un trilocale con terrazzo a Milano.",
    answer: "Raccolgo zona, budget e caratteristiche desiderate, poi preparo la richiesta per l’agente più adatto.",
    benefits: [
      ["⌂", "Presentazione immobili", "Racconta caratteristiche, zona, servizi e documentazione disponibile."],
      ["◎", "Contatti qualificati", "Raccoglie budget, preferenze e tempistiche prima del contatto commerciale."],
      ["▤", "Documenti e materiali", "Conosce schede, capitolati, planimetrie e informazioni dell’agenzia."],
      ["↗", "Visite su WhatsApp", "Prepara la richiesta e facilita l’appuntamento con l’agente."],
    ],
    useCases: ["Ricerca e vendita immobili", "Nuove costruzioni", "Affitti e locazioni", "Appuntamenti e visite"],
  },
};

export const sectorCards = [
  ["hotel", "Hotel", "Concierge digitale per ospiti e reception."],
  ["benessere", "Benessere", "Consulente AI per trattamenti e appuntamenti."],
  ["ristorazione", "Ristorazione", "Menu parlante, territorio e prenotazioni."],
  ["immobiliare", "Immobiliare", "Presentazione immobili e contatti qualificati."],
];
