create table if not exists public.commercial_leads (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  company text not null,
  email text not null,
  phone text not null,
  category text,
  plan text,
  message text,
  source text not null default 'website',
  status text not null default 'new' check (status in ('new','contacted','qualified','won','lost')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  avatar_client_id uuid not null unique references public.avatar_clients(id) on delete cascade,
  display_name text,
  role text not null default 'owner' check (role in ('owner','editor','viewer')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.avatar_usage_events (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.avatar_clients(id) on delete cascade,
  event_type text not null check (event_type in ('chat','speech','lead','document','website')),
  units integer not null default 1 check (units >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.avatar_clients
  add column if not exists plan_code text not null default 'business',
  add column if not exists monthly_chat_limit integer not null default 1000,
  add column if not exists monthly_speech_character_limit integer not null default 120000,
  add column if not exists commercial_status text not null default 'active';

create index if not exists commercial_leads_created_at_idx on public.commercial_leads(created_at desc);
create index if not exists customer_profiles_avatar_client_id_idx on public.customer_profiles(avatar_client_id);
create index if not exists avatar_usage_events_client_created_idx on public.avatar_usage_events(client_id, created_at desc);
create index if not exists avatar_usage_events_type_idx on public.avatar_usage_events(client_id, event_type, created_at desc);

alter table public.commercial_leads enable row level security;
alter table public.customer_profiles enable row level security;
alter table public.avatar_usage_events enable row level security;

drop policy if exists "Customers read own profile" on public.customer_profiles;
create policy "Customers read own profile" on public.customer_profiles for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Customers read own avatar" on public.avatar_clients;
create policy "Customers read own avatar" on public.avatar_clients for select to authenticated using (id in (select avatar_client_id from public.customer_profiles where user_id = (select auth.uid()) and active = true));

drop policy if exists "Customers read own usage" on public.avatar_usage_events;
create policy "Customers read own usage" on public.avatar_usage_events for select to authenticated using (client_id in (select avatar_client_id from public.customer_profiles where user_id = (select auth.uid()) and active = true));

revoke all on public.commercial_leads from anon, authenticated;
revoke insert, update, delete on public.avatar_usage_events from anon, authenticated;
grant select on public.customer_profiles, public.avatar_clients, public.avatar_usage_events to authenticated;
